### ISSUE TITLE
Local changes to files don't always get served locally

### ISSUE THREAD

**Issue by hmc-cs-jbearer** [hmc-cs-jbearer/MusicHack#9]
Sometimes when I change a source file, the corresponding changes don't pop up in the browser right away. I have no idea why and I can't reliably reproduce the behavior. The problem always goes away after a few page reloads/server restarts, but this is really frustrating when trying to test some quick changes.

EDIT: Opening the app in a new incognito window seems to refresh all local changes consistently. Maybe the browser is somehow caching the old copies of the pages?

**Comment by jbearer** [comment]
To fix this (in Chrome): open Chrome developer tools settings. Make sure `Disable cache (while DevTools is open)` is checked.
